remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Mich-Will Portfolio of Cybersecurity Projects
description: Showcasing skills and personal projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-modernist
